"""Student-facing layered error analysis demo."""


def student_analysis_ui_html() -> str:
    return r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>数学记忆智能体 · 错题分析</title>
<style>
:root{--ink:#203230;--muted:#60716d;--paper:#f5f5ef;--card:#fff;--line:#dce4de;--green:#176d60;--dark:#104c44;--soft:#e8f3ee;--orange:#d37c47;--shadow:0 12px 32px rgba(34,56,49,.07)}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.65 "Microsoft YaHei","PingFang SC",Arial,sans-serif}button,input{font:inherit}a{color:var(--green);text-decoration:none}a:hover{text-decoration:underline}
.top{height:68px;background:rgba(255,255,255,.94);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 max(20px,calc((100vw - 1180px)/2));position:sticky;top:0;z-index:10}.brand{font-weight:800;display:flex;align-items:center;gap:10px}.mark{height:34px;width:34px;background:var(--green);border-radius:10px;color:white;display:grid;place-items:center;font:23px Georgia}.top small{color:var(--muted)}
main{max-width:1180px;margin:auto;padding:36px 22px 90px}.hero{background:radial-gradient(circle at 88% 12%,#e0f3e9 0,transparent 35%),linear-gradient(125deg,#fdfdfa,#edf5ed);border:1px solid #d8e7dd;border-radius:24px;padding:42px 48px 38px}.eyebrow{font-size:12px;letter-spacing:.14em;color:var(--green);font-weight:800}.hero h1{font-size:clamp(30px,4.5vw,49px);letter-spacing:-.045em;line-height:1.2;margin:10px 0 8px}.hero p{margin:0 0 25px;color:var(--muted)}.ask{display:flex;gap:10px;padding:8px;background:white;border:1px solid #cbded1;border-radius:15px;box-shadow:var(--shadow);max-width:790px}.ask input{flex:1;min-width:0;border:0;outline:0;padding:10px 14px;background:transparent}.ask button{border:0;border-radius:10px;padding:10px 23px;background:var(--green);color:white;font-weight:700;cursor:pointer}.ask button:disabled{opacity:.6}.examples{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.examples button{border:1px solid #cbded1;color:var(--green);background:#fbfffb;padding:5px 12px;border-radius:999px;cursor:pointer}
.hidden{display:none!important}.status{margin:28px 0;padding:26px;background:white;border:1px solid var(--line);border-radius:16px;color:var(--muted)}.crumb{margin:26px 0 10px;color:var(--muted);font-size:13px}.titleline{display:flex;justify-content:space-between;align-items:end;gap:16px;flex-wrap:wrap;margin:18px 0 18px}.titleline h2{font-size:28px;margin:0}.titleline p{color:var(--muted);margin:4px 0 0}.pill{display:inline-block;background:var(--soft);color:var(--dark);border-radius:999px;padding:5px 12px;font-size:12px;font-weight:700}
.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:20px 0 31px}.metric{background:white;border:1px solid var(--line);border-radius:16px;padding:19px}.metric strong{display:block;font-size:28px;line-height:1.25}.metric span{font-size:12px;color:var(--muted)}
.section-head{display:flex;justify-content:space-between;align-items:center;gap:15px;margin:28px 0 15px}.section-head h3{font-size:21px;margin:0}.section-head small{color:var(--muted)}.category-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.category{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:22px;box-shadow:var(--shadow)}.category-top{display:flex;justify-content:space-between;align-items:start;gap:16px}.category h4{font-size:19px;margin:0}.category .count{font:700 26px Georgia;color:var(--green)}.category .count small{font:12px Arial;color:var(--muted)}.track{height:8px;background:#edf1eb;border-radius:8px;overflow:hidden;margin:17px 0}.track span{display:block;height:100%;background:linear-gradient(90deg,var(--green),#69a990)}.category p{margin:12px 0;color:var(--muted);font-size:13px}.tags{display:flex;gap:6px;flex-wrap:wrap}.tag{font-size:12px;padding:4px 9px;background:#f0f4f0;border-radius:8px;color:#526a60}.category a,.summary-card a{font-weight:700;display:inline-block;margin-top:14px}
.domain-breakdown{background:#f6f8f5;border-radius:10px;padding:11px 13px;margin-top:13px;font-size:12px;color:var(--muted)}.domain-breakdown strong{display:block;color:var(--ink);margin-bottom:4px}.domain-breakdown span{display:inline-block;margin-right:11px;white-space:nowrap}.point-label{font-size:12px;color:var(--muted);margin:14px 0 6px}
.summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.summary-card{background:white;border:1px solid var(--line);border-radius:18px;padding:23px;min-height:225px}.summary-card .number{font:700 13px Georgia;color:var(--orange);letter-spacing:.1em}.summary-card h4{font-size:19px;margin:9px 0 10px}.summary-card p{margin:0;color:var(--muted);font-size:14px}.summary-card strong{color:var(--ink)}
.detail{background:white;border:1px solid var(--line);border-radius:18px;padding:25px;margin:17px 0}.detail h3{margin:0 0 10px}.detail p{color:var(--muted)}.freq-row{display:grid;grid-template-columns:115px minmax(0,1fr) 60px;gap:12px;align-items:center;margin:13px 0}.freq-row .track{margin:0}.weak-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.weak-item{border:1px solid var(--line);border-radius:13px;padding:16px}.weak-item h4{margin:0 0 5px}.weak-item small{color:var(--muted)}.case-list{display:grid;gap:12px}.case-row{display:block;background:white;border:1px solid var(--line);border-radius:14px;padding:17px 20px}.case-row:hover{border-color:#9bc8b0;text-decoration:none}.case-row h4{margin:5px 0;color:var(--ink);font-size:16px}.case-row p{margin:7px 0;color:var(--muted);font-size:13px}.case-row .trigger{border-left:3px solid var(--orange);padding-left:10px;color:#6a5547}.case-meta{font-size:12px;color:var(--green);font-weight:700}.more{display:block;margin:17px auto;border:1px solid var(--green);color:var(--green);background:white;border-radius:10px;padding:9px 18px;cursor:pointer}.case-pair{display:grid;grid-template-columns:1fr;gap:20px}.figure{margin:0;border:1px solid var(--line);border-radius:12px;overflow:hidden}.figure img{display:block;width:100%;height:auto}.figure figcaption{padding:9px 13px;background:#f5f8f5;font-size:12px;color:var(--muted)}.diagnosis{border-left:4px solid var(--orange);background:#fff7f0;padding:15px 19px;border-radius:8px}.diagnosis p{margin:6px 0;color:var(--ink);white-space:pre-wrap}.source-note{color:var(--muted);font-size:12px;margin-top:24px}.math{overflow-wrap:anywhere}
.frequency-note{background:#edf6f0;border-left:4px solid var(--green)}.frequency-note p{color:var(--ink);line-height:1.9;margin:0}.domain-frequency{padding:3px 0 12px;border-bottom:1px solid var(--line)}.domain-frequency:last-child{border-bottom:0}.domain-frequency small{display:block;color:var(--muted);margin-left:127px}
.practice-panel{margin-top:34px;padding:28px;background:linear-gradient(130deg,#ecf6ef,#fff);border:1px solid #cfe4d6;border-radius:20px}.practice-panel h3{margin:0 0 6px;font-size:22px}.practice-panel p{margin:0 0 18px;color:var(--muted)}.practice-form{display:flex;gap:10px;max-width:780px}.practice-form input{flex:1;min-width:0;padding:11px 15px;border:1px solid #bed7c7;border-radius:10px;background:white}.practice-form button{border:0;border-radius:10px;padding:10px 20px;background:var(--green);color:white;font-weight:700;cursor:pointer}.practice-form button:disabled{opacity:.6}.practice-list{display:grid;gap:13px;margin-top:22px}.practice-question{background:white;border:1px solid var(--line);border-radius:14px;padding:18px 20px}.practice-question small{color:var(--green);font-weight:700}.practice-question h4{margin:8px 0;font-size:18px;font-weight:600}.practice-question a{font-size:12px}.practice-error{color:#a44235;margin-top:14px}
@media(max-width:800px){main{padding:20px 14px 60px}.hero{padding:27px 20px}.category-grid,.summary-grid,.weak-list{grid-template-columns:1fr}.metrics{grid-template-columns:1fr}.top{padding:0 14px}.top small{display:none}.freq-row{grid-template-columns:110px minmax(0,1fr) 50px}.domain-frequency small{margin-left:0}}
</style>
<script>window.MathJax={tex:{inlineMath:[['\\(','\\)'],['$','$']],displayMath:[['\\[','\\]'],['$$','$$']],processEscapes:true},startup:{typeset:false}};</script>
<script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" onload="typesetMath()"></script>
</head><body>
<header class="top"><div class="brand"><span class="mark">∫</span>数学记忆智能体</div><small>错题分析 · 多模态记忆</small></header>
<main><section class="hero"><div class="eyebrow">错题诊断和回访</div><h1>从过去的解题中，找到下一步</h1><p>输入时间和数学方向，查看错因分类、高频模式、薄弱点与每道题的错误触发位置。</p>
<form id="form" class="ask"><input id="query" aria-label="输入错题分析问题" value="帮我收集分析过去3个月的错题" autocomplete="off"><button id="submit" type="submit">生成分析</button></form>
<div class="examples"><button data-q="帮我收集分析过去3个月的错题">过去3个月</button><button data-q="分析过去7个月的几何错题">几何 · 7个月</button><button data-q="分析过去7个月的概率统计错题">概率统计 · 7个月</button><button data-q="分析过去3个月的微积分错题">微积分 · 3个月</button></div></section>
<div id="status" class="status hidden"></div><div id="content"></div></main>
<script>
const root='/student-v2', $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function mathRich(value){const text=String(value??'').trim();if(!text)return '';return text.split(/\r?\n/).map(line=>{let part=line.trim();if(!part)return '<br>';if(/[\$]|\\\(|\\\[/.test(part))return esc(part);if(/^[A-Za-z0-9\s+\-*/=^_().×÷≤≥≠π√∫∑∞]+$/u.test(part)&&/[=^_∫√×÷]/u.test(part))return `<span>\\(\\displaystyle ${esc(part)}\\)</span>`;return esc(part)}).join('<br>')}
function typesetMath(){const root=$('content');if(!root||!window.MathJax?.typesetPromise)return;try{window.MathJax.typesetClear?.([root]);window.MathJax.typesetPromise([root]).catch(()=>{})}catch(_){}}
let report=null, practiceSet=null, pageSize=20;
function qs(q){return '?q='+encodeURIComponent(q)}
function link(path){return root+path+qs(report.request)}
function date(x){return x?x.slice(0,10):'全部时间'}
function range(){let w=report.time_window;return w.from?`${date(w.from)} 至 ${date(w.to)}`:'全部时间'}
function showStatus(text){$('status').textContent=text;$('status').classList.remove('hidden');$('content').innerHTML=''}
function hideStatus(){$('status').classList.add('hidden')}
function title(name,detail){return `<div class="titleline"><div><h2>${esc(name)}</h2><p>${esc(detail)}</p></div><span class="pill">${esc(range())}</span></div>`}
function breadcrumb(label){return `<div class="crumb"><a href="${link('')}">分析总览</a>　/　${esc(label)}</div>`}
function categoryCard(c){const points=c.top_knowledge_points.slice(0,3);return `<article class="category"><div class="category-top"><h4>${esc(c.label)}</h4><div class="count">${c.count}<small> 道</small></div></div><div class="domain-breakdown"><strong>数学方向分布 · 合计 ${c.count} 道</strong>${c.domains.map(x=>`<span>${esc(x.name)} ${x.count}</span>`).join('')}</div><div class="track"><span style="width:${(c.share*100).toFixed(1)}%"></span></div><p>占本期模型判错题目的 ${(c.share*100).toFixed(1)}%；${c.trigger_available} 道识别到首个错误步骤。</p><div class="point-label">常见知识点（前 3，单题可关联多个）</div><div class="tags">${points.map(x=>`<span class="tag">${esc(x.name)} · ${x.error_count}</span>`).join('')||'<span class="tag">暂无明确知识点</span>'}</div><a href="${link('/types/'+encodeURIComponent(c.error_type))}">查看本类错题与触发点 →</a></article>`}
function practiceCards(data){return `<div class="practice-list">${data.questions.map(item=>`<article class="practice-question"><small>第 ${item.number} 题 · ${esc(item.domain)} · ${esc(item.error_type)}</small><h4 class="math">${mathRich(item.question)}</h4><div class="tags"><span class="tag">巩固：${esc(item.knowledge_point)}</span><span class="tag">关联 ${item.related_error_count} 道历史错题</span></div><a href="${link('/cases/'+encodeURIComponent(item.source_attempt_id))}">查看对应的历史错题 →</a></article>`).join('')}</div>`}
function practiceSection(){return `<section class="practice-panel"><h3>05 · 高频错题变式练习</h3><p>根据本期高频错因与知识点生成新题，先独立完成，再按需要回访对应错题。</p><form id="practiceForm" class="practice-form"><input id="practicePrompt" aria-label="输入变式练习要求" value="根据我的错题分析记录再出5题来练手巩固"><button id="practiceSubmit" type="submit">生成新题</button></form><div id="practiceResult">${practiceSet&&practiceSet.analysis_request===report.request?practiceCards(practiceSet):''}</div></section>`}
function overview(){const c=report.coverage, top=report.categories[0], weak=report.weaknesses[0], located=report.cases.filter(x=>x.trigger).length;
return `${title('错题分析总览',`本期 ${c.cohort_attempts} 道作答，已完成诊断 ${c.diagnosed_attempts} 道。`)}
<div class="metrics"><div class="metric"><strong>${c.error_attempts}</strong><span>模型判断为错误的题目</span></div><div class="metric"><strong>${report.categories.length}</strong><span>错误类型</span></div><div class="metric"><strong>${located}</strong><span>找到首个错误步骤的题目</span></div></div>
<div class="section-head"><h3>01 · 错误类型分类</h3><small>每道错题归入一种主要错因，点击查看完整证据</small></div><div class="category-grid">${report.categories.map(categoryCard).join('')||'<div class="detail">当前范围没有模型判错题目。</div>'}</div>
<div class="section-head"><h3>继续查看</h3></div><div class="summary-grid"><article class="summary-card"><div class="number">02 / FREQUENCY</div><h4>高频错误统计分析</h4><p>${top?`最多的是<strong>${esc(top.label)}</strong>，共 <strong>${top.count}</strong> 道，占错题 ${(top.share*100).toFixed(1)}%。`:'暂无错题可统计。'} 按错误类型、数学方向和月份进一步查看。</p><a href="${link('/frequency')}">查看频次详情 →</a></article>
<article class="summary-card"><div class="number">03 / WEAKNESS</div><h4>每类问题的薄弱点</h4><p>${weak?`出现最多的知识点是<strong>${esc(weak.knowledge_point)}</strong>，关联 ${weak.error_count} 道错题。`:'暂无知识点证据。'} 按错误类型查看反复出现的知识点。</p><a href="${link('/weaknesses')}">查看薄弱点详情 →</a></article>
<article class="summary-card"><div class="number">04 / TRIGGERS</div><h4>逐题错误原因与触发点</h4><p>本期 ${c.error_attempts} 道错题中，${located} 道有首个错误步骤。逐题查看诊断、手写原图与标注图。</p><a href="${link('/cases')}">查看全部错题 →</a></article></div>${footnote()}${practiceSection()}`}
function footnote(){return `<p class="source-note">统计依据：当前 Seed 模型诊断及教师修订；每个数字均可追溯到题目。知识点错误率的分母为同期已诊断且标注该知识点的作答。模型判断有误时可在单题页由教师修订。</p>`}
function frequency(){
 const maxType=Math.max(1,...report.categories.map(x=>x.count)),maxDomain=Math.max(1,...(report.domains||[]).map(x=>x.count)),maxMonth=Math.max(1,...report.monthly.map(x=>x.total));
 return `${breadcrumb('高频错误统计分析')}${title('高频错误统计分析',`共 ${report.coverage.error_attempts} 道模型判错题目。`)}
 <section class="detail frequency-note"><h3>分析与建议</h3><p>${esc(report.frequency_summary||'暂无可用统计总结。')}</p></section>
 <section class="detail"><h3>按错误类型</h3>${report.categories.map(c=>`<div class="freq-row"><span>${esc(c.label)}</span><div class="track"><span style="width:${c.count/maxType*100}%"></span></div><strong>${c.count}</strong></div>`).join('')||'暂无数据'}</section>
 <section class="detail"><h3>按数学方向 · 合计 ${report.coverage.error_attempts} 道</h3>${(report.domains||[]).map(d=>`<div class="domain-frequency"><div class="freq-row"><span>${esc(d.name)}</span><div class="track"><span style="width:${d.count/maxDomain*100}%"></span></div><strong>${d.count}</strong></div><small>模型判错 ${d.count}/${d.attempt_count} 道（${(d.model_error_rate*100).toFixed(1)}%） · 主要类型：${esc(d.types.slice(0,3).map(t=>`${t.label} ${t.count}`).join('、'))}</small></div>`).join('')||'暂无数据'}</section>
 <section class="detail"><h3>按月份</h3>${report.monthly.map(m=>`<div class="freq-row"><span>${esc(m.month)}</span><div class="track"><span style="width:${m.total/maxMonth*100}%"></span></div><strong>${m.total}</strong></div><small>${esc(report.categories.filter(c=>m.types[c.error_type]).map(c=>`${c.label} ${m.types[c.error_type]}`).join(' · '))}</small>`).join('')||'暂无月份记录'}</section>${footnote()}`
}
function weaknesses(){return `${breadcrumb('每类问题的薄弱点')}${title('每类问题的薄弱点','知识点按该类错题中的出现次数排序；同时列出同期该知识点的总作答数。')}${report.categories.map(c=>`<section class="detail"><h3><a href="${link('/types/'+encodeURIComponent(c.error_type))}">${esc(c.label)} · ${c.count} 道 →</a></h3><div class="weak-list">${c.top_knowledge_points.map(p=>`<div class="weak-item"><h4>${esc(p.name)}</h4><small>该类错误 ${p.error_count} 次 · 同期相关作答 ${p.attempt_count} 次</small></div>`).join('')||'<p>模型未给出稳定的知识点标签。</p>'}</div></section>`).join('')}${footnote()}`}
function caseRow(c){let trigger=c.trigger?`第 ${Number(c.first_error_step)+1} 步：${c.trigger}`:'首个错误步骤未定位';return `<a class="case-row" href="${link('/cases/'+encodeURIComponent(c.attempt_id))}"><div class="case-meta">${esc(c.error_label)} · ${esc(c.domain_label)} · ${esc(date(c.time))}</div><h4 class="math">${mathRich(c.question||c.attempt_id)}</h4><p>${mathRich(c.explanation)}</p><p class="trigger">${mathRich(trigger)}</p><div class="tags">${c.knowledge_points.slice(0,4).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></a>`}
function cases(type){const category=report.categories.find(x=>x.error_type===type), list=type?report.cases.filter(x=>x.error_type===type):report.cases;const name=category?category.label:'逐题错误原因与触发点';const count=Math.min(pageSize,list.length);return `${breadcrumb(name)}${title(name,`共 ${list.length} 道错题；逐题保留原因、首个错误步骤与图片。`)}${category?`<section class="detail"><h3>本类集中出现的知识点</h3><div class="tags">${category.top_knowledge_points.map(x=>`<span class="tag">${esc(x.name)} · ${x.error_count} 道</span>`).join('')}</div></section>`:''}<div class="case-list">${list.slice(0,count).map(caseRow).join('')}</div>${count<list.length?`<button class="more" id="more">继续显示（${count}/${list.length}）</button>`:''}${footnote()}`}
function oneCase(id){const c=report.cases.find(x=>x.attempt_id===id);if(!c)return `<div class="status">没有找到这道题。</div>`;const image='/v1/attempts/'+encodeURIComponent(id)+'/image',audit='/v1/attempts/'+encodeURIComponent(id)+'/audit?model='+encodeURIComponent(report.model);return `${breadcrumb('题目详情')}${title('错误原因与触发点',`${c.error_label} · ${c.domain_label} · ${date(c.time)}`)}<section class="detail"><h3 class="math">${mathRich(c.question||id)}</h3><div class="tags">${c.knowledge_points.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="diagnosis"><strong>错误原因</strong><p class="math">${mathRich(c.explanation)}</p><strong>错误触发点</strong><p class="math">${c.trigger?`第 ${Number(c.first_error_step)+1} 步：${mathRich(c.trigger)}`:'模型未定位到具体步骤，请结合原图核对。'}</p></div><div class="case-pair"><figure class="figure"><a href="${image}" target="_blank"><img src="${image}" alt="手写数学作答原图"></a><figcaption>原始手写作答 · 点击查看原尺寸</figcaption></figure><figure class="figure" id="auditFigure"><a href="${audit}" target="_blank"><img id="auditImage" src="${audit}" alt="可审计错题标注图"></a><figcaption>错误定位与更正 · 点击查看原尺寸</figcaption></figure></div><p class="source-note">来源：${c.display_source==='teacher_override'?'教师修订':'Seed 模型诊断'} · 题目 ID：${esc(id)}</p><p><a href="/review?attempt_id=${encodeURIComponent(id)}&model=${encodeURIComponent(report.model)}">教师修改 VLM 诊断或订正 →</a></p></section>`}
function render(){if(!report)return;hideStatus();let path=decodeURIComponent(location.pathname.slice(root.length));if(path===''||path==='/')$('content').innerHTML=overview();else if(path==='/frequency')$('content').innerHTML=frequency();else if(path==='/weaknesses')$('content').innerHTML=weaknesses();else if(path==='/cases')$('content').innerHTML=cases();else if(path.startsWith('/types/'))$('content').innerHTML=cases(path.slice(7));else if(path.startsWith('/cases/'))$('content').innerHTML=oneCase(path.slice(7));else $('content').innerHTML='<div class="status">页面不存在。</div>';let more=$('more');if(more)more.onclick=()=>{pageSize+=20;render()};let audit=$('auditImage');if(audit)audit.onerror=()=>{$('auditFigure').innerHTML='<figcaption>这道题暂时没有可用的标注图。</figcaption>'};let form=$('practiceForm');if(form)form.onsubmit=generatePractice;typesetMath()}
async function generatePractice(e){e.preventDefault();const request=$('practicePrompt').value.trim();if(!request)return;const button=$('practiceSubmit'),result=$('practiceResult');button.disabled=true;result.textContent='正在根据错题记录生成变式题…';try{const response=await fetch('/v1/memory/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysis_request:report.request,request})});const data=await response.json();if(!response.ok)throw Error(data.error||'生成失败');practiceSet=data;result.innerHTML=practiceCards(data);typesetMath()}catch(error){result.innerHTML='<div class="practice-error">'+esc(error.message)+'</div>'}finally{button.disabled=false}}
async function run(q){q=q.trim();if(!q)return;pageSize=20;practiceSet=null;$('query').value=q;$('submit').disabled=true;showStatus('正在汇总历史错题与模型诊断…');try{const response=await fetch('/v1/memory/error-analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request:q})});const data=await response.json();if(!response.ok)throw Error(data.error||'分析失败');report=data;render()}catch(error){showStatus('分析失败：'+error.message)}finally{$('submit').disabled=false}}
$('form').onsubmit=e=>{e.preventDefault();history.pushState(null,'',root+qs($('query').value));run($('query').value)};document.querySelectorAll('.examples button').forEach(b=>b.onclick=()=>{history.pushState(null,'',root+qs(b.dataset.q));run(b.dataset.q)});let initial=new URLSearchParams(location.search).get('q');if(initial)run(initial);window.onpopstate=()=>{const q=new URLSearchParams(location.search).get('q');if(q&&report?.request===q)render();else if(q)run(q);else{$('content').innerHTML='';hideStatus()}};
</script></body></html>'''
